services:
    _defaults:
        autowire: true
        public: true

    Chaplean\Bundle\FormHandlerBundle\Form\ControllerFormHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\FormHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\PersisterSuccessHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\AngularFailureHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\ControllerExceptionHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\ControllerSuccessHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\ControllerFailureHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\NoOperationHandler: ~

    chaplean_form_handler.form_handler:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\ControllerFormHandler

    chaplean_form_handler.form.handler.no_operation:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\NoOperationHandler

    chaplean_form_handler.form.controller_form_handler:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\ControllerFormHandler

    chaplean_form_handler.form_handler.form_handler:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\FormHandler

    chaplean_form_handler.success_handler.persister:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\PersisterSuccessHandler

    chaplean_form_handler.failure_handler.angular:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\AngularFailureHandler

    chaplean_form_handler.exception_handler.controller:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\ControllerExceptionHandler

    chaplean_form_handler.success_handler.controller:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\ControllerSuccessHandler

    chaplean_form_handler.failure_handler.controller:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\ControllerFailureHandler

    chaplean_form_handler.handler.no_operation:
        alias: Chaplean\Bundle\FormHandlerBundle\Form\NoOperationHandler
