services:
    chaplean_form_handler.form_handler:
        class: Chaplean\Bundle\FormHandlerBundle\Form\FormHandler
        arguments:
            - '@service_container'
            - 'chaplean_form_handler.form.handler'
            - 'chaplean_form_handler.success_handler.controller_wrapped'
            - 'chaplean_form_handler.failure_handler.controller_wrapped'
            - '@fos_rest.view_handler.default'

    chaplean_form_handler.form.handler:
        class: Chaplean\Bundle\FormHandlerBundle\Form\FormHandler
        arguments: ['@form.factory']

    chaplean_form_handler.success_handler.persister:
        class: Chaplean\Bundle\FormHandlerBundle\Form\PersisterSuccessHandler
        arguments: ['@doctrine']

    chaplean_form_handler.failure_handler.angular:
        class: Chaplean\Bundle\FormHandlerBundle\Form\AngularFailureHandler

    chaplean_form_handler.success_handler.controller_wrapped:
        class: Chaplean\Bundle\FormHandlerBundle\Form\ControllerWrappedSuccessHandler
        arguments: ['@doctrine']

    chaplean_form_handler.failure_handler.controller_wrapped:
        class: Chaplean\Bundle\FormHandlerBundle\Form\ControllerWrappedFailureHandler

    chaplean_form_handler.form.handler.no_operation:
        class: Chaplean\Bundle\FormHandlerBundle\Form\NoOperationHandler
