services:
    _defaults:
        autowire: true
        public: true

    Chaplean\Bundle\FormHandlerBundle\Form\ControllerFormHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\FormHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\PersisterSuccessHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\AngularFailureHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\ControllerExceptionHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\ControllerSuccessHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\ControllerFailureHandler: ~
    Chaplean\Bundle\FormHandlerBundle\Form\NoOperationHandler: ~

    chaplean_form_handler.form_handler:
        alias: chaplean_form_handler.form.controller_form_handler

    chaplean_form_handler.form.handler.no_operation:
        alias: chaplean_form_handler.handler.no_operation

    chaplean_form_handler.form.controller_form_handler:
        class: Chaplean\Bundle\FormHandlerBundle\Form\ControllerFormHandler
        arguments:
            - '@service_container'
            - '@chaplean_form_handler.form_handler.form_handler'
            - '@chaplean_form_handler.success_handler.controller'
            - '@chaplean_form_handler.failure_handler.controller'
            - '@chaplean_form_handler.exception_handler.controller'
            - '@fos_rest.view_handler.default'

    chaplean_form_handler.form_handler.form_handler:
        class: Chaplean\Bundle\FormHandlerBundle\Form\FormHandler
        arguments: ['@form.factory']

    chaplean_form_handler.success_handler.persister:
        class: Chaplean\Bundle\FormHandlerBundle\Form\PersisterSuccessHandler
        arguments: ['@doctrine.orm.entity_manager']

    chaplean_form_handler.failure_handler.angular:
        class: Chaplean\Bundle\FormHandlerBundle\Form\AngularFailureHandler

    chaplean_form_handler.exception_handler.controller:
        class: Chaplean\Bundle\FormHandlerBundle\Form\ControllerExceptionHandler

    chaplean_form_handler.success_handler.controller:
        class: Chaplean\Bundle\FormHandlerBundle\Form\ControllerSuccessHandler
        arguments: ['@doctrine.orm.entity_manager']

    chaplean_form_handler.failure_handler.controller:
        class: Chaplean\Bundle\FormHandlerBundle\Form\ControllerFailureHandler

    chaplean_form_handler.handler.no_operation:
        class: Chaplean\Bundle\FormHandlerBundle\Form\NoOperationHandler
